node{
    try{        
        stage('Checkout Project'){
            checkout([
                $class: 'GitSCM',
                branches: [[name: '*/main']],
                doGenerateSubmoduleConfigurations: false,
                extensions: [[$class: 'CleanCheckout']],
                submoduleCfg: [],
                userRemoteConfigs: [[credentialsId: 'git-generate-video', url: 'git@github.com:denakop/generate-video-with-python.git']]
            ])    
        }

        stage('Build') {
          withAWS(credentials: 'jenkins-aws') {
            withEnv([
                'ELASTICSEARCH_HOSTS=$ELASTICSEARCH_HOSTS', 
                'ELASTICSEARCH_API_ID=$ELASTICSEARCH_API_ID', 
                'ELASTICSEARCH_API_KEY=$ELASTICSEARCH_API_KEY', 
                'DATABASE_HOST=$DATABASE_HOST',
                'DATABASE_PORT=$DATABASE_PORT',
                'DATABASE_USER=$DATABASE_USER',
                'DATABASE_PASSWORD=$DATABASE_PASSWORD',
                'DATABASE_NAME=$DATABASE_NAME',
                'JENKINS_URL=$JENKINS_URL',
                'JENKINS_USERNAME=$JENKINS_USERNAME',
                'JENKINS_PASSWORD=$JENKINS_PASSWORD',
                'ACCOUNT_ID=$ACCOUNT_ID']) {
              echo env.ACCOUNT_ID
            }
            
            ansiblePlaybook( 
                playbook: '/var/lib/jenkins/ansible/generate-video-with-python.yaml',
                inventory: '/var/lib/jenkins/ansible/inventory'
            )
          }
        }

    } catch (e) {
            throw e
        } finally {
        }
}