def notifySlack(String buildStatus = 'STARTED') {
    // Build status of null means success.
    buildStatus = buildStatus ?: 'SUCCESS'

    def color

    if (buildStatus == 'STARTED') {
        color = '#D4DADF'
    } else if (buildStatus == 'SUCCESS') {
        color = '#BDFFC3'
    } else if (buildStatus == 'UNSTABLE') {
        color = '#FFFE89'
    } else {
        color = '#FF9FA1'
    }

    def msg = "${buildStatus}: `${env.JOB_NAME}` #${env.BUILD_NUMBER}:\n${env.BUILD_URL}"

    slackSend(color: color, message: msg)
}

node('jenkins-ubuntu-slave'){
    try{
        notifySlack()
        
        stage('Checkout Project'){
            checkout([
                $class: 'GitSCM',
                branches: [[name: '*/main']],
                doGenerateSubmoduleConfigurations: false,
                extensions: [[$class: 'CleanCheckout']],
                submoduleCfg: [],
                userRemoteConfigs: [[credentialsId: 'git-generate-video', url: 'git@github.com:denakop/generate-video-with-python.git']]
            ])    
        }

        stage('Build') {
          withAWS(credentials: 'jenkins-aws') {
            withEnv([
                'ELASTICSEARCH_HOSTS=$ELASTICSEARCH_HOSTS', 
                'ELASTICSEARCH_API_ID=$ELASTICSEARCH_API_ID', 
                'ELASTICSEARCH_API_KEY=$ELASTICSEARCH_API_KEY', 
                'DATABASE_HOST=$DATABASE_HOST',
                'DATABASE_PORT=$DATABASE_PORT',
                'DATABASE_USER=$DATABASE_USER',
                'DATABASE_PASSWORD=$DATABASE_PASSWORD',
                'DATABASE_NAME=$DATABASE_NAME',
                'JENKINS_URL=$JENKINS_URL',
                'JENKINS_USERNAME=$JENKINS_USERNAME',
                'JENKINS_PASSWORD=$JENKINS_PASSWORD',
                'ACCOUNT_ID=$ACCOUNT_ID']) {
              echo env.ACCOUNT_ID
            }
            
            ansiblePlaybook( 
                playbook: '/home/ubuntu/ansible/generate-video-with-python.yaml',
                inventory: '/home/ubuntu/ansible/inventory'
            )
          }
        }

    } catch (e) {
            currentBuild.result = 'FAILURE'
            throw e
        } finally {
            notifySlack(currentBuild.result)
        }
}